### ISSUE TITLE
Research unit testing on the front end

### ISSUE THREAD

**Issue by jackbrewer7** [cs130-w21/3#107]
Unit testing is necessary in software development. In this part of the project, you are required to
design and encode test cases with expected outcomes to prove that your code-under-test is
correct for the realized use cases.

Task this week is to research front end unit testing, understand the selected framework, and maybe complete one test.

**Comment by maddywestergaard** [comment]
https://blog.bitsrc.io/7-react-testing-libraries-you-should-know-b20ca97422a4

Jest & Enzyme:
https://blog.bitsrc.io/how-to-test-react-components-using-jest-and-enzyme-fab851a43875

ReactTestUtils:
https://reactjs.org/docs/test-utils.html
