### ISSUE TITLE
Change profile privacy settings

### ISSUE THREAD

**Issue by jayjmanley** [cs130-w21/3#12]
## User Story
As a user, I would like change my profile privacy settings to public, private, or friends only so that I can be in control of who can view my profile.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

**Comment by mfarber99** [comment]
Users will only be able to see their own profile or that of their friends, so privacy settings will not be needed
