### ISSUE TITLE
View Progress

### ISSUE THREAD

**Issue by jayjmanley** [cs130-w21/3#13]
## User Story
As a user, I would like to be able to see a graph or chart of certain parameters (i.e. specific workout weight) over time so that I can see my progress.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

**Comment by mfarber99** [comment]
No longer a feature we will be implementing
