### ISSUE TITLE
Add graph type: Specific exercises

### ISSUE THREAD

**Issue by jayjmanley** [cs130-w21/3#14]
## User Story
As a user, I would like to be able to see the graph of my various exercise statistics over time so that I can see progress in my exercises.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

**Comment by mfarber99** [comment]
Collapsing this into one user story for progress since it's very similar to another one
