### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#29]
## Task
Describe the classes and data structures of your application and their attributes, relations and operations with a Class Diagram.

**Comment by jackbrewer7** [comment]
@startuml
package Model {

class Workout {
  -id : String {id}
  -userEmail : String
  -name : String
  -exercises : String [1..*] {unique}
  -daysOfWeek : Integer [1..*] {unique}
  --
  +getId() : String
  +setId(in id : String) : void
  +getUserEmail() : String
  +setUserEmail(in userEmail : String) : void
  +getName() : String
  +setName(in name : String) : void
  +getExercises() : String [1..*] {unique}
  +setExercises(in exercises : String [1..*] {unique}) : void
  +getDaysOfWeek() : Integer [1..*] {unique}
  +setDaysOfWeek(in daysOfWeek : Integer [1..*] {unique}) : void
}

class ExerciseWeight {
  -id : String {id}
  -userEmail : String
  -name : String 
  -sets : Integer 
  -reps : Integer 
  -weight : Integer 
  -exerciseType : String 
  --
  +getId() : String
  +setId(in id : String) : void
  +getUserEmail() : String
  +setUserEmail(in userEmail : String) : void
  +getName() : String
  +setName(in name : String) : void
  +getSets() : Integer
  +setSets(in sets : Integer) : void
  +getReps() : Integer
  +setReps(in reps : Integer) : void
  +getWeight() : Integer
  +setWeight(in weight : Integer) : void
  +getExerciseType() : String
  +setExerciseType(in exerciseType: String) : void
}

class ExerciseRun {
  -id : String {id}
  -userEmail : String
  -name : String 
  -miles: Double
  -exerciseType : String 
  --
  +getId() : String
  +setId(in id : String) : void
  +getUserEmail() : String
  +setUserEmail(in userEmail : String) : void
  +getName() : String
  +setName(in name : String) : void
  +getMiles() : Double
  +setMiles(in miles : Double) : void
  +getExerciseType() : String
  +setExerciseType(in exerciseType: String) : void
}

class Account {
  -email : String {id}
  -username : String
  -password : String
  -friends : String [1..*] {unique}
  --
  +getEmail() : String
  +setEmail(in email : String) : void
  +getUsername() : String
  +setUsername(in username : String) : void
  +getPassword() : String
  +setPassword(in password : String) : void
  +getFriends() : String [1..*] {unique}
  +setFriends(in friends : String [1..*] {unique}) : void
}

Workout "*" --> "1..*" ExerciseWeight : references
Workout "*" --> "1..*" ExerciseRun : references
Account "*" <--> "*" Account: references
}

package DAO {

class WeightExerciseDao {
  -mapper : DynamoDBMapper
  --
  +getWeightExercises(in userEmail : String) : ExerciseWeight [*] {ordered}
  +putWeightExercise(in exercise : ExerciseWeight) : void
  +updateWeightExercise(in exercise : ExerciseWeight) : void
  +removeWeightExercise(in exercise : ExerciseWeight) : void
}

class RunExerciseDao {
  -mapper : DynamoDBMapper
  --
  +getRunExercises(in userEmail : String) : ExerciseRun [*] {ordered}
  +putRunExercise(in exercise : ExerciseRun) : void
  +updateRunExercise(in exercise : ExerciseRun) : void
  +removeRunExercise(in exercise : ExerciseRun) : void
}

class AccountDao {
  -mapper : DynamoDBMapper
  --
  +createAccount(in username : String, in email : String, in password : String) : Account
  +login(in email : String, in password : String) : Account
  +getFriends(in email : String) : String [*] {unique}
  +addFriend(in userEmail : String, in friendEmail : String) : void
  +removeFriend(in userEmail : String, in friendEmail : String) : void
}

class WorkoutDao {
  -mapper : DynamoDBMapper
  --
  +getWorkouts(in userEmail : String) : Workout [*] {ordered}
  +putWorkout(in workout : Workout) : void
  +updateWorkout(in workout : Workout) : void
  +removeWorkout(in workout : Workout) : void
}

WorkoutDao ..> Workout
AccountDao ..> Account
RunExerciseDao ..> ExerciseRun
WeightExerciseDao ..> ExerciseWeight
}
@enduml

**Comment by mfarber99** [comment]
Thanks for updating this, I forgot 

Photo [here](http://www.plantuml.com/plantuml/png/tLV1Jjmm4BtlLrXxeb1MwXLL2Agb4WTA1Qque1xIU4Wj4YUr4oX2_7jdifbeOcz80r8FN10ypvlnl3UUNOvydRYwAV95bQItIGRghDIGgyV58iqJxzLLwMxBfaP0gNsZrO6wh9sncNeq-ecmneCxAHAJzqU4sgI00G1_mAN6W-zHTVrXjThzeHuRQtutq2RJoOC_lxa2kCMmKrj31cvRt3x-sCkWFjKxxsIPFTzYnYfnLOguAutkED_vmY5L7c66eB4uqHViCSv1AD6b0Y7pXCKGzBXDJ2T3CUUqY46XTQydLfAAngLaCDMQj49MU-9nuUjUWSb-lMvg525uBI_g4-IW2g7xjbe0ibZV7YgHz0rCpoLg8ktig0GJTIXPmBs0AkPsC7AbjX5tusdCvWFaXqQ4SoyiYNkNfppj_3U7Za_SHMDVFsw5oS4Vg7NP_CpXJG_H6NLAL6wMg0mZjrMYF_qFFXwdQTdORcK0DntR67soLCY-BvqUW3VEWDNZUr8wEE94xm9VPjHAkzK5Fc4ZdtFZQzT3d8LFA4lOQPZbSzlqz8SA1rBEAQ6aKVnTOBcxHFKErP92by7EntW7D-30fk2Ve_2Z7SJp553yHoBGBnqe0-aw_8rbVNmklg-qb-3ywwJS35IHL1KuckS7zA5SVpfh0Ja6GwOVVNzXlzUa5he23dGhSDK4kUGZYFZImwRIIGql93ieohlvPFa6qOwNA8Uq6R9Xz5RD41-_DZDZjURHMAUPj71B_RCwgGEyOyVQkWdUArun0Xfvx5oUCkTbPkpEV6wmAw84Sda4coFHUaEBJERIl4-61x7whqlp5FnpCcTMEyhud7BIRJFAR2BVTs4z8HxDwMYfoLGqjowQNgqEEO8t9yFijfXpFX83lf3h8exOd6BH8x2wAVA_)
