### ISSUE TITLE
Create state machine diagrams

### ISSUE THREAD

**Issue by jackbrewer7** [cs130-w21/3#31]
Describe the behavior of your most complex classes (of the system as a whole) and how it responds to events with State Machine Diagrams.
Please include one or two state machine diagrams showing your most important components in your application.

**Comment by coltonmeskell** [comment]
http://www.plantuml.com/plantuml/uml/ZPGzRzim48Pt_ef3bWA50-yPYhXr0tHgbqo11rgys6mbKY2FIOCY_xraJmVgGt43PA1vxtCVUe-vZQG3fQvL3nyFS7tz2NPDuvEZ_UuxtC1zn03MFNg8wTXP8ZH0v-3JwGpttvJADE4O-QC095CJC4U7e2J3Jjjs0ocVdUvm0zePw7MCppwONAfFD4hH-fDr4_IoNXjp5omwisGU_zr_Y7p5f0mmxRJCmFTNUqtwg2DUWOw3Ql-vXkzofXJ6qN8pwkUhQy9BJrZwGJw3DAzW52xYBm4rIpaNI4F--1CRsa3KJmZukmyOe_LEmO0mBkrbFWldj88gAEhI8GiDF3pfrXe1-0CTr9oe0rRGkbKKfc9q55vWMnRdEVVVO4-bVGNp5Sb1Ix0DI2cu-G2luXOlHNQ9JvUnTI-PNBLIWbCd1O2RVD9cKKJYREGPcry_P4UPUFCpmqnUpMdAVULaRmvgMgwsEofbtNkBLRoMhFoow6LFnQJw4jzyJlmWrpsGw632o0UXn8WKCTJtFJScAgX4mRcddJ4OviQmSFd9namT_8J4jGUvq15fWHWFMssa02S6yYjQMUNK6qtupW9rOtJ-BMNKV7J-iTYJ2xFN5FzzoDLk6M7jVz2hod-tMPMwzYy0

**Comment by coltonmeskell** [comment]
@startuml
[*] --> AccountDAO : User info submitted through UI

state AccountDAO {
  [*] --> createAccount : User email, username, and password input
  [*] --> login : User email and password input
  [*] --> addFriend : User email and friend's email input

state createAccount {
  state "Database" as createDB
  state "Failure" as createFail
  [*] --> Encrypted : encrypt password
  Encrypted --> Created : create Account object, save expression
  Created --> createDB : save Account object
  createDB --> [*] : saved [valid Account email]

  createDB --> createFail : saved [invalid Account email]
  createFail : entry /throw exception

  createAccount : exit /return Account object
}

state login {
  login : exit /return Account object
  state "Database" as loginDB
  state "Failure" as loginFail
  [*] --> loginDB : load Account object
  loginDB --> CheckPassword : loaded [valid Account email]
  CheckPassword --> [*] : checked [valid password]

  loginDB --> loginFail : loaded [invalid Account email]
  CheckPassword --> loginFail : checked [invalid password]

  loginFail : entry /throw exception
}

state addFriend {
  state "Database" as friendDB
  state "Failure" as friendFail
  
  [*] --> friendDB : load user and friend Account objects
  friendDB --> FriendAdder : loaded [valid friend Account email]
  FriendAdder : entry /get user Account friend set
  FriendAdder : do /add friend email to set
  FriendAdder : exit /update user Account friend set
  FriendAdder --> [*] : added friend

  friendDB --> friendFail : loaded [invalid friend Account email]

  friendFail : entry /throw exception

  addFriend : exit /save Account object
}

}
@enduml
